import { trpc } from "@/lib/trpc";
import { ArrowRight, Check, ChevronRight, CircleDot, CloudCog, Github, Image, Loader2, Plus, Sparkles, TerminalSquare, Unplug } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

type Project = { id: number; name: string };

function useProjectContext() {
  const { data: overview, isLoading } = trpc.workspace.overview.useQuery();
  const projects = (overview?.projects ?? []) as Project[];
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const projectId = selectedId ?? projects[0]?.id ?? null;
  const snapshot = trpc.workspace.companionSnapshot.useQuery({ projectId: projectId ?? 1 }, { enabled: Boolean(projectId) });
  return { projects, projectId, setSelectedId, isLoading, snapshot };
}

function ProjectChooser({ projects, projectId, onChange }: { projects: Project[]; projectId: number | null; onChange: (id: number) => void }) {
  return <div className="tool-project-chooser"><span>Project context</span><select value={projectId ?? ""} onChange={(event) => onChange(Number(event.target.value))}>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></div>;
}

function NoProject({ icon: Icon, title, detail }: { icon: typeof Github; title: string; detail: string }) {
  const [, setLocation] = useLocation();
  return <section className="tool-no-project"><Icon className="size-8" /><p className="eyebrow">PROJECT CONTEXT REQUIRED</p><h1>{title}</h1><p>{detail}</p><button className="subby-primary-button" onClick={() => setLocation("/projects")}>Open project hub <ArrowRight className="size-4" /></button></section>;
}

export function GitHubTool() {
  const { projects, projectId, setSelectedId, isLoading, snapshot } = useProjectContext();
  const utils = trpc.useUtils();
  const [branch, setBranch] = useState("main");
  const [remoteUrl, setRemoteUrl] = useState("");
  const [notes, setNotes] = useState("");
  useEffect(() => { if (snapshot.data?.repository) { setBranch(snapshot.data.repository.defaultBranch); setRemoteUrl(snapshot.data.repository.remoteUrl ?? ""); setNotes(snapshot.data.repository.notes ?? ""); } }, [snapshot.data?.repository]);
  const save = trpc.workspace.saveRepositoryProfile.useMutation({ onSuccess: async () => { if (projectId) await utils.workspace.companionSnapshot.invalidate({ projectId }); toast.success("Repository plan saved."); }, onError: (error) => toast.error(error.message) });
  if (!isLoading && !projects.length) return <NoProject icon={Github} title="Give your repository plan a project home." detail="Create a project first, then record the intended repository and branch details without connecting GitHub." />;
  return <section className="tool-page"><ToolHeading eyebrow="GITHUB READINESS" title="Prepare the repository before you connect it." detail="GitHub is not connected yet. Capture repository context locally now, then connect your account later without losing the plan." icon={Github} /><ProjectChooser projects={projects} projectId={projectId} onChange={setSelectedId} /><div className="tool-grid two"><section className="subby-panel tool-form-panel"><div className="tool-status"><Unplug className="size-4" /><span>Not connected — no GitHub account access is required</span></div><form className="subby-form" onSubmit={(event) => { event.preventDefault(); if (projectId) save.mutate({ projectId, remoteUrl, defaultBranch: branch, notes: notes || undefined }); }}><label>Repository URL <span>optional</span><input value={remoteUrl} onChange={(event) => setRemoteUrl(event.target.value)} placeholder="https://github.com/account/repository" /></label><label>Default branch<input required value={branch} onChange={(event) => setBranch(event.target.value)} placeholder="main" /></label><label>Repository notes <span>optional</span><textarea rows={6} value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Record the repository purpose, ownership, conventions, or connection checklist." /></label><button className="subby-primary-button w-full" disabled={save.isPending}>{save.isPending ? "Saving plan…" : "Save repository plan"}<Check className="size-4" /></button></form></section><aside className="tool-guidance"><CircleDot className="size-5" /><h2>What works now</h2><p>Your repository plan is project-scoped and persisted. It is deliberately separate from external access and does not store GitHub credentials.</p><div className="guidance-step"><span>01</span><p>Record the intended remote and default branch.</p></div><div className="guidance-step"><span>02</span><p>Capture team conventions or a connection checklist.</p></div><div className="guidance-step"><span>03</span><p>Connect GitHub later when you are ready.</p></div></aside></div></section>;
}

export function TerminalTool() {
  const { projects, projectId, setSelectedId, isLoading, snapshot } = useProjectContext();
  const utils = trpc.useUtils();
  const [command, setCommand] = useState("");
  const [description, setDescription] = useState("");
  const create = trpc.workspace.createCommandDraft.useMutation({ onSuccess: async () => { if (projectId) await utils.workspace.companionSnapshot.invalidate({ projectId }); setCommand(""); setDescription(""); toast.success("Runbook step added."); }, onError: (error) => toast.error(error.message) });
  const update = trpc.workspace.updateCommandState.useMutation({ onSuccess: () => projectId && utils.workspace.companionSnapshot.invalidate({ projectId }), onError: (error) => toast.error(error.message) });
  if (!isLoading && !projects.length) return <NoProject icon={TerminalSquare} title="Create a project to assemble a runbook." detail="Command drafts are kept as a project-scoped plan until an isolated terminal environment is connected." />;
  const nextState = (state: "draft" | "review" | "ready") => state === "draft" ? "review" : state === "review" ? "ready" : "draft";
  return <section className="tool-page"><ToolHeading eyebrow="COMMAND RUNBOOK" title="Plan commands before execution." detail="Build a reviewable terminal runbook now. Execution remains unavailable until a controlled workspace runner is connected." icon={TerminalSquare} /><ProjectChooser projects={projects} projectId={projectId} onChange={setSelectedId} /><div className="tool-grid terminal-grid"><section className="subby-panel tool-form-panel"><form className="subby-form" onSubmit={(event) => { event.preventDefault(); if (projectId) create.mutate({ projectId, command, description: description || undefined }); }}><label>Command<input required value={command} onChange={(event) => setCommand(event.target.value)} placeholder="pnpm test" /></label><label>Purpose <span>optional</span><textarea rows={4} value={description} onChange={(event) => setDescription(event.target.value)} placeholder="What should this command verify or prepare?" /></label><button className="subby-primary-button w-full" disabled={create.isPending}>{create.isPending ? "Adding step…" : "Add runbook step"}<Plus className="size-4" /></button></form><p className="tool-disclaimer"><Unplug className="size-3.5" /> Commands are saved for review, not executed from this page.</p></section><section className="subby-panel tool-list-panel"><div className="panel-heading"><div><p className="eyebrow">SAVED STEPS</p><h2>Command runbook</h2></div><span className="record-count">{snapshot.data?.commands.length ?? 0}</span></div>{snapshot.isLoading ? <ToolLoading /> : snapshot.data?.commands.length ? <div className="runbook-list">{snapshot.data.commands.map((item) => <article key={item.id} className="runbook-item"><div><code>$ {item.command}</code>{item.description && <p>{item.description}</p>}</div><button className={`state-button ${item.state}`} onClick={() => update.mutate({ id: item.id, state: nextState(item.state) })}>{item.state}<ChevronRight className="size-3.5" /></button></article>)}</div> : <ToolEmpty title="No command steps yet" detail="Add build, test, lint, or migration commands that deserve a deliberate review." />}</section></div></section>;
}

export function DeploymentsTool() {
  const { projects, projectId, setSelectedId, isLoading, snapshot } = useProjectContext();
  const utils = trpc.useUtils();
  const [environment, setEnvironment] = useState<"development" | "staging" | "production">("development");
  const [targetUrl, setTargetUrl] = useState("");
  const create = trpc.workspace.createDeploymentPlan.useMutation({ onSuccess: async () => { if (projectId) await utils.workspace.companionSnapshot.invalidate({ projectId }); setTargetUrl(""); toast.success("Release plan added."); }, onError: (error) => toast.error(error.message) });
  const update = trpc.workspace.updateDeploymentState.useMutation({ onSuccess: () => projectId && utils.workspace.companionSnapshot.invalidate({ projectId }), onError: (error) => toast.error(error.message) });
  if (!isLoading && !projects.length) return <NoProject icon={CloudCog} title="Start a project before planning a release." detail="Deployment plans are stored inside each project, ready for a provider connection when you decide to add one." />;
  const nextState = (state: "planned" | "ready" | "released") => state === "planned" ? "ready" : state === "ready" ? "released" : "planned";
  return <section className="tool-page"><ToolHeading eyebrow="RELEASE PLANS" title="Make release intent visible early." detail="Capture a release path by environment without connecting a deployment provider. Update its readiness as the project moves forward." icon={CloudCog} /><ProjectChooser projects={projects} projectId={projectId} onChange={setSelectedId} /><div className="tool-grid terminal-grid"><section className="subby-panel tool-form-panel"><form className="subby-form" onSubmit={(event) => { event.preventDefault(); if (projectId) create.mutate({ projectId, environment, targetUrl }); }}><label>Environment<select value={environment} onChange={(event) => setEnvironment(event.target.value as typeof environment)}><option value="development">Development</option><option value="staging">Staging</option><option value="production">Production</option></select></label><label>Target URL <span>optional</span><input type="url" value={targetUrl} onChange={(event) => setTargetUrl(event.target.value)} placeholder="https://app.example.com" /></label><button className="subby-primary-button w-full" disabled={create.isPending}>{create.isPending ? "Adding release…" : "Add release plan"}<Plus className="size-4" /></button></form><p className="tool-disclaimer"><Unplug className="size-3.5" /> No deployment provider is connected. This is a persisted release plan.</p></section><section className="subby-panel tool-list-panel"><div className="panel-heading"><div><p className="eyebrow">RELEASE TRACKER</p><h2>Planned environments</h2></div><span className="record-count">{snapshot.data?.deployments.length ?? 0}</span></div>{snapshot.isLoading ? <ToolLoading /> : snapshot.data?.deployments.length ? <div className="runbook-list">{snapshot.data.deployments.map((item) => <article key={item.id} className="deployment-item"><div><strong>{item.environment}</strong><span>{item.targetUrl || "No target URL recorded"}</span></div><button className={`state-button ${item.state}`} onClick={() => update.mutate({ id: item.id, state: nextState(item.state) })}>{item.state}<ChevronRight className="size-3.5" /></button></article>)}</div> : <ToolEmpty title="No release plans" detail="Add a development, staging, or production environment to establish the delivery path." />}</section></div></section>;
}

export function MediaTool() {
  const { projects, projectId, setSelectedId, isLoading, snapshot } = useProjectContext();
  const utils = trpc.useUtils();
  const [prompt, setPrompt] = useState("");
  const generate = trpc.workspace.generateMediaImage.useMutation({ onSuccess: async () => { if (projectId) await utils.workspace.companionSnapshot.invalidate({ projectId }); setPrompt(""); toast.success("Project image generated."); }, onError: (error) => toast.error(error.message) });
  if (!isLoading && !projects.length) return <NoProject icon={Image} title="Create a project before generating an asset." detail="Generated media is stored in a selected project’s asset history so its creative context stays attached to the work." />;
  return <section className="tool-page"><ToolHeading eyebrow="MEDIA STUDIO" title="Generate project visuals from a focused brief." detail="Create images for the selected project with SUBBY’s built-in media service. Each generated image is saved in the project’s media history." icon={Image} /><ProjectChooser projects={projects} projectId={projectId} onChange={setSelectedId} /><div className="tool-grid media-grid"><section className="subby-panel tool-form-panel"><div className="media-callout"><Sparkles className="size-4" /><span>Image generation may take a short while. Be specific about subject, mood, lighting, framing, and intended use.</span></div><form className="subby-form" onSubmit={(event) => { event.preventDefault(); generate.mutate({ projectId, prompt }); }}><label>Image brief<textarea rows={8} required minLength={12} maxLength={2500} value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="A refined graphite product illustration for a developer dashboard, soft indigo accents, widescreen, no text" /></label><button className="subby-primary-button w-full" disabled={generate.isPending}>{generate.isPending ? <><Loader2 className="size-4 animate-spin" /> Generating image…</> : <><Sparkles className="size-4" /> Generate project image</>}</button></form></section><section className="subby-panel media-gallery"><div className="panel-heading"><div><p className="eyebrow">ASSET HISTORY</p><h2>Generated images</h2></div><span className="record-count">{snapshot.data?.media.length ?? 0}</span></div>{snapshot.isLoading ? <ToolLoading /> : snapshot.data?.media.length ? <div className="media-grid-list">{snapshot.data.media.map((asset) => <a href={asset.url} target="_blank" rel="noreferrer" key={asset.id} className="media-card"><img src={asset.url} alt={asset.prompt} /><span>{asset.prompt}</span></a>)}</div> : <ToolEmpty title="No images generated" detail="Describe the first image you need for this project and SUBBY will save it here." />}</section></div></section>;
}

function ToolHeading({ eyebrow, title, detail, icon: Icon }: { eyebrow: string; title: string; detail: string; icon: typeof Github }) { return <div className="tool-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{detail}</p></div><div className="tool-heading-icon"><Icon className="size-5" /></div></div>; }
function ToolLoading() { return <div className="tool-loading"><Loader2 className="size-4 animate-spin" /> Loading project tool data…</div>; }
function ToolEmpty({ title, detail }: { title: string; detail: string }) { return <div className="tool-empty"><p>{title}</p><span>{detail}</span></div>; }
